---
- name: Create text file in root directory
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  
  tasks:
    - name: Create a.txt file
      copy:
        content: "File created by Ansible\n"
        dest: /home/semaphore/a.txt
        owner: semaphore
        group: semaphore
        mode: '0644'
