---
- name: Create text file in root directory
  hosts: all
  become: yes
  tasks:
    - name: Create a.txt file
      copy:
        content: "File created by Ansible\n"
        dest: /root/a.txt
        owner: root
        group: root
        mode: '0644'
