---
- name: Create text file in root directory
  hosts: all
  remote_user: root
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: "/root/.ssh/id_ed25519"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  
  tasks:
    - name: Create a.txt file
      copy:
        content: "File created by Ansible\n"
        dest: /root/a.txt
        owner: root
        group: root
        mode: '0644'
